// <auto-generated />
using System;
using EEM4QC_HFT_2021221.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EEM4QC_HFT_2021221.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211024154234_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployee", b =>
                {
                    b.Property<int>("Emp_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emp_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Emp_Is_Existed")
                        .HasColumnType("bit");

                    b.Property<string>("Emp_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emp_Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_Id");

                    b.ToTable("Hr_Employees");

                    b.HasData(
                        new
                        {
                            Emp_Id = 1,
                            Emp_Code = "1",
                            Emp_Is_Existed = false,
                            Emp_Name = "Sevinj",
                            Emp_Surname = "Abdullayeva"
                        },
                        new
                        {
                            Emp_Id = 2,
                            Emp_Code = "2",
                            Emp_Is_Existed = false,
                            Emp_Name = "James",
                            Emp_Surname = "Bond"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeCredentials", b =>
                {
                    b.Property<int>("Empc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Empc_EmployeeEmp_Id")
                        .HasColumnType("int");

                    b.Property<int>("Empc_Employee_Id")
                        .HasColumnType("int");

                    b.Property<string>("Empc_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empc_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Empc_Id");

                    b.HasIndex("Empc_EmployeeEmp_Id");

                    b.ToTable("Hr_Employee_Credentials");

                    b.HasData(
                        new
                        {
                            Empc_Id = 1,
                            Empc_Employee_Id = 1,
                            Empc_Mail = "sevinj160@yahoo.com",
                            Empc_Password = "sevinj"
                        },
                        new
                        {
                            Empc_Id = 2,
                            Empc_Employee_Id = 2,
                            Empc_Mail = "oktay0@yahoo.com",
                            Empc_Password = "oktay"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeStatus", b =>
                {
                    b.Property<int>("Emps_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emps_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emps_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HrEmployeeEmp_Id")
                        .HasColumnType("int");

                    b.HasKey("Emps_Id");

                    b.HasIndex("HrEmployeeEmp_Id");

                    b.ToTable("Hr_Employee_Status");

                    b.HasData(
                        new
                        {
                            Emps_Id = 1,
                            Emps_Description = "5 years experience",
                            Emps_Title = "developer"
                        },
                        new
                        {
                            Emps_Id = 2,
                            Emps_Description = "1 year experience",
                            Emps_Title = "database administrator"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeWorkDetails", b =>
                {
                    b.Property<int>("Wd_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Wd_About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wd_Employee_Exit_Detail_Id")
                        .HasColumnType("int");

                    b.Property<int>("Wd_Employee_Id")
                        .HasColumnType("int");

                    b.Property<int>("Wd_Employee_Status_Id")
                        .HasColumnType("int");

                    b.Property<int>("Wd_Experience")
                        .HasColumnType("int");

                    b.Property<bool>("Wd_Is_Exited")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Wd_Join_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Wd_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wd_Manager")
                        .HasColumnType("int");

                    b.Property<string>("Wd_Summary_Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wd_Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wd_Work_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wd_Work_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Wd_Id");

                    b.ToTable("Hr_Employee_Work_Details");

                    b.HasData(
                        new
                        {
                            Wd_Id = 1,
                            Wd_Employee_Exit_Detail_Id = 1,
                            Wd_Employee_Id = 1,
                            Wd_Employee_Status_Id = 1,
                            Wd_Experience = 0,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Budapest",
                            Wd_Manager = 0,
                            Wd_Title = "developer",
                            Wd_Work_Mail = "sevinj160@yahoo.com",
                            Wd_Work_Phone = "36203106684"
                        },
                        new
                        {
                            Wd_Id = 2,
                            Wd_Employee_Exit_Detail_Id = 2,
                            Wd_Employee_Id = 2,
                            Wd_Employee_Status_Id = 2,
                            Wd_Experience = 0,
                            Wd_Is_Exited = false,
                            Wd_Join_Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Wd_Location = "Debrecen",
                            Wd_Manager = 0,
                            Wd_Title = "database administrator",
                            Wd_Work_Mail = "oktay0@yahoo.com",
                            Wd_Work_Phone = "36207896656"
                        });
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeCredentials", b =>
                {
                    b.HasOne("EEM4QC_HFT_2021221.Models.HrEmployee", "Empc_Employee")
                        .WithMany()
                        .HasForeignKey("Empc_EmployeeEmp_Id");

                    b.Navigation("Empc_Employee");
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployeeStatus", b =>
                {
                    b.HasOne("EEM4QC_HFT_2021221.Models.HrEmployee", null)
                        .WithMany("HrEmployees")
                        .HasForeignKey("HrEmployeeEmp_Id");
                });

            modelBuilder.Entity("EEM4QC_HFT_2021221.Models.HrEmployee", b =>
                {
                    b.Navigation("HrEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
